function station(label, options = {}) {
  return {
    label,
    displayName: options.displayName ?? label,
    aliases: options.aliases ?? [],
    interchanges: options.interchanges ?? [],
    stationId: options.stationId ?? null,
  };
}

export const RAPID_LINE_LAYOUTS = {
  '1': {
    routeId: '1',
    routeName: 'Line 1 Yonge-University',
    type: 'u',
    stations: [
      station('Vaughan Metropolitan Centre'),
      station('Highway 407'),
      station('Pioneer Village'),
      station('York University'),
      station('Finch West'),
      station('Downsview Park'),
      station('Sheppard West'),
      station('Wilson'),
      station('Yorkdale'),
      station('Lawrence West'),
      station('Glencairn'),
      station('Eglinton West (Cedarvale)', { aliases: ['Eglinton West', 'Cedarvale'], interchanges: ['5'] }),
      station('St Clair West'),
      station('Dupont'),
      station('Spadina', { interchanges: ['2'] }),
      station('St George', { interchanges: ['2'] }),
      station('Museum'),
      station("Queen's Park"),
      station('St Patrick'),
      station('Osgoode'),
      station('St Andrew'),
      station('Union', { aliases: ['Union Station'], interchanges: ['GO', 'UP'], stationId: '13815' }),
      station('King'),
      station('Queen'),
      station('TMU', { aliases: ['Dundas'] }),
      station('College'),
      station('Wellesley'),
      station('Bloor-Yonge', { aliases: ['Bloor Station', 'Yonge Station'], interchanges: ['2'], stationId: '13864' }),
      station('Rosedale'),
      station('Summerhill'),
      station('St Clair'),
      station('Davisville'),
      station('Eglinton', { interchanges: ['5'] }),
      station('Lawrence'),
      station('York Mills'),
      station('Sheppard-Yonge', { interchanges: ['4'] }),
      station('North York Centre'),
      station('Finch'),
    ],
  },
  '2': {
    routeId: '2',
    routeName: 'Line 2 Bloor-Danforth',
    type: 'horizontal',
    stations: [
      station('Kipling'),
      station('Islington'),
      station('Royal York'),
      station('Old Mill'),
      station('Jane'),
      station('Runnymede'),
      station('High Park'),
      station('Keele'),
      station('Dundas West'),
      station('Lansdowne'),
      station('Dufferin'),
      station('Ossington'),
      station('Christie'),
      station('Bathurst'),
      station('Spadina', { interchanges: ['1'], stationId: '13852' }),
      station('St George', { interchanges: ['1'], stationId: '13856' }),
      station('Bay'),
      station('Bloor-Yonge', { aliases: ['Yonge Station', 'Bloor Station'], interchanges: ['1'], stationId: '13756' }),
      station('Sherbourne'),
      station('Castle Frank'),
      station('Broadview'),
      station('Chester'),
      station('Pape'),
      station('Donlands'),
      station('Greenwood'),
      station('Coxwell'),
      station('Woodbine'),
      station('Main Street'),
      station('Victoria Park'),
      station('Warden'),
      station('Kennedy', { interchanges: ['5'] }),
    ],
  },
  '4': {
    routeId: '4',
    routeName: 'Line 4 Sheppard',
    type: 'horizontal',
    stations: [
      station('Sheppard-Yonge', { interchanges: ['1'] }),
      station('Bayview'),
      station('Bessarion'),
      station('Leslie'),
      station('Don Mills'),
    ],
  },
  '5': {
    routeId: '5',
    routeName: 'Line 5 Eglinton',
    type: 'horizontal',
    stations: [
      station('Mount Dennis'),
      station('Keelesdale'),
      station('Caledonia'),
      station('Fairbank'),
      station('Oakwood'),
      station('Cedarvale', { aliases: ['Eglinton West', 'Eglinton West (Cedarvale)'], interchanges: ['1'] }),
      station('Forest Hill'),
      station('Chaplin'),
      station('Avenue'),
      station('Eglinton', { interchanges: ['1'] }),
      station('Mount Pleasant'),
      station('Leaside'),
      station('Laird'),
      station('Sunnybrook Park'),
      station('Don Valley'),
      station('Aga Khan Park & Museum'),
      station('Wynford'),
      station('Sloane'),
      station("O'Connor"),
      station('Pharmacy'),
      station('Hakimi Lebovic'),
      station('Golden Mile'),
      station('Birchmount'),
      station('Ionview'),
      station('Kennedy', { interchanges: ['2'] }),
    ],
  },
};

